### ISSUE TITLE
A typo in README.md

### ISSUE THREAD

**Issue by Arkitect-z** [facebookresearch/hot3d#10]
Hi, I found a typo in

[Link](https://github.com/facebookresearch/hot3d/blob/f8cfbb677ebded5f6b084c99446d45466367733b/README.md?plain=1#L139C19-L139C34),

where "-sequence_folder" was input twice in here and the following commands.

**Comment by SeaOtocinclus** [comment]
Thank you for reporting, we will fix it.

**Comment by SeaOtocinclus** [comment]
Thank you for your report @Arkitect-z, we have fixed the typo.
