### ISSUE TITLE
Turning off logging

### ISSUE THREAD

**Issue by Shashvatb** [facebookresearch/hot3d#13]
Hi @SeaOtocinclus
I've been trying to turn off the logging when loading the data. Is there an existing functionality that can turn this off or any small changes that can fix this easily? The std-out uses up way too many resources

**Comment by SeaOtocinclus** [comment]
Unfortunately not for now, most of the logging is coming from a library we are using (projectaria_tools).
- Can you precise exactly which piece of log is not good for you (so we could see the source of it and see if we could adjust?)

**Comment by SeaOtocinclus** [comment]
Those logs are coming from ProjectAria_tools, see here a related issues on the project https://github.com/facebookresearch/projectaria_tools/issues/109

You can try redirect the logs to a file, as a temporary solution, else the code solution would be to make log configurable in projectaria_tools.

**Comment by Shashvatb** [comment]
Thank you for this information!

**Comment by SeaOtocinclus** [comment]
Closing the issue as the main reason has been identified and unfortunately is in a dependency we are using and not in HOT3D codebase by itself.
