### ISSUE TITLE
Data Missing

### ISSUE THREAD

**Issue by Shashvatb** [facebookresearch/hot3d#17]
Hello,

For the sequence P0014_24cb3bf0 there seems to be some data missing/download links seem to be wrong (There seems to be no MPS data)

Best regards,
Shashvat

**Comment by ligengen** [comment]
This sequence does not contain mps_slam data as you can see in the screenshot below. And the online calibration fails:
```python
online_calibration = self._mps_data_provider.get_online_calibration(
RuntimeError: Cannot query for online calibration since the data is not available
```
![image](https://github.com/user-attachments/assets/3a672348-7d52-4cac-a266-1d51ca0e6843)
