### ISSUE TITLE
Data type main_vrs is not available for quest sequence

### ISSUE THREAD

**Issue by ruddradev** [facebookresearch/hot3d#18]
Hello,

When I try to download any of the quest sequences via the Download script, I get this error and the recording.vrs is no longer downloaded. This issue does not occur in the Aria sequences as the VRS is available there.

I also tried to print sequences.keys() to see what are the available values for quest sequences and got this answer - 

dict_keys(['video_main_rgb', 'ground_truth', 'hand_data'])

**Comment by SeaOtocinclus** [comment]
Hello,
Thank you for reporting the issue, we will investigate, and I will keep you informed.

**Comment by Chris10M** [comment]
@SeaOtocinclus +1 I also face the same issue. The download JSON for the Quest does not contain the VRS links.

**Comment by SeaOtocinclus** [comment]
@Chris10M , @ruddradev we found the issue and are currently working on fixing it.
We will ping here again when the data has been re-exported and available for you to download.

**Comment by SeaOtocinclus** [comment]
@Chris10M, @ruddradev 
Situation is back to normal, sorry for the inconvenience.

Please download again the `Hot3DQuest_download_urls.json` file from https://www.projectaria.com/datasets/hot3d/ and you will be all good.

```
% python dataset_downloader_main.py -c /Users/pierrem/Downloads/Hot3DQuest_download_urls.json -o ./dataset_test -l P0002_1464cbdc -d all 
Downloading the following sequences: ['P0002_1464cbdc']
Creating local output folder ./dataset_test
downloading sequence P0002_1464cbdc to ./dataset_test/P0002_1464cbdc
Serializing to /var/folders/gf/j34cvzpx21l35qhmphhkyc1r0000gn/T/tmpcrb5v80w/Hot3DQuest_v3.0.1_P0002_1464cbdc_main_recording.vrs
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.85G/2.85G [00:58<00:00, 49.1MiB/s]
Serializing to /var/folders/gf/j34cvzpx21l35qhmphhkyc1r0000gn/T/tmpzl4vg_q8/Hot3DQuest_v3.0.1_P0002_1464cbdc_ground_truth.zip
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.85M/2.85M [00:00<00:00, 16.4MiB/s]
Serializing to /var/folders/gf/j34cvzpx21l35qhmphhkyc1r0000gn/T/tmpgvw3u6ma/Hot3DQuest_v3.0.1_P0002_1464cbdc_hand_data.zip
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.67M/3.67M [00:00<00:00, 18.2MiB/s]
Renaming main vrs from ./dataset_test/P0002_1464cbdc/Hot3DQuest_v3.0.1_P0002_1464cbdc_main_recording.vrs to ./dataset_test/P0002_1464cbdc/recording.vrs
1 of 1 sequences are successfully downloaded
```

**Comment by ruddradev** [comment]
Thanks, this is working.

**Comment by SeaOtocinclus** [comment]
Happy to hear, thank you for confirming @ruddradev
