### ISSUE TITLE
Recording own datasets from in-house quest

### ISSUE THREAD

**Issue by ruddradev** [facebookresearch/hot3d#19]
Hello team,

Thanks for the excellent work on hand-object interaction datasets. We have a Meta Quest Pro in out lab, and were wondering if it is possible to record datasets in the same format as the one in HOT3D from it? If not directly, is there any policy or process we can go through to enable out Quest to record the datasets?

Warm Regards,
Ruddra

**Comment by SeaOtocinclus** [comment]
Thank you for your kind words about the dataset.

- Unfortunately, the Quest Headset SDK does not allow retrieving images while performing captures.
- But note that Project Aria is a device that can be accessible to Academic Partner and could help you capture ego-centric dataset at scale ==> https://www.projectaria.com/research-kit/

I would also advise you to read our Dataset Whitepaper to know more about how we captured and built the dataset (see Ground-truth annotations) in "Introducing HOT3D: An Egocentric Dataset for 3D Hand and Object Tracking" https://arxiv.org/pdf/2406.09598
