### ISSUE TITLE
An error is occurred when the viewer is launched

### ISSUE THREAD

**Issue by taeyunwoo** [facebookresearch/hot3d#4]
Hello,
Thanks for your work!

I have followed your instruction, and I'm trying to execute the viewer as below code:
`pixi run viewer --sequence_folder --sequence_folder <PATH>/hot3d_dataset/P0001_0444739e> --object_library_folder <PATH>/hot3d_dataset/assets/`

In my environment, this command has been changed as follows:
`pixi run viewer  --sequence_folder ./dataset/P0002_1464cbdc --object_library_folder ./dataset/assets/ --mano_model_folder ./mano_model`

However, this command occurs an error:
args provided: Namespace(sequence_folder='./dataset/P0002_1464cbdc/', object_library_folder='./dataset/assets/', mano_model_folder='./mano_model', hand_type='UMETRACK', jpeg_quality=75, rrd_output_path=None)
An exception occurred: SequenceDatasetPathsBase.__init__() takes 2 positional arguments but 3 were given

Do I need another options for it?
Thanks for your reply!

**Comment by SeaOtocinclus** [comment]
Hello @taeyunwoo, thank you for your feedback and reporting exactly the sequence and command line you have used.
I will investigate soon and come back to you.

**Comment by SeaOtocinclus** [comment]
Investigation shown this bug has been introduced by 4f49bd0649d84cfe7e2e1c5da579715f3309384e, impacting only Quest sequences; a fix is coming your way!

**Comment by SeaOtocinclus** [comment]
Issue fixed by 72a751e51facc3e71ea8050a31cdd43701688aa1
Please update your repo and let us know by acknowledged and/or closing the issue.

**Comment by taeyunwoo** [comment]
Dear @SeaOtocinclus, appreciate your revision of the code!
I will re-clone the repo, and check it.

Thank you for your work!
