### ISSUE TITLE
How can I access to the image files.

### ISSUE THREAD

**Issue by taeyunwoo** [facebookresearch/hot3d#7]
First of all, thank you for your works.
(Also, the viewer.py works well after I pull your commit. I also appreciate to it.)

How can I access to the image files?
I trying to train my model which gets an input image (of egocentric hands), and estimates the hand poses.

However, in your README.md in github, I could not find an instruction for the images.
(I finished Step.3, and I have some .json, .csv, and .jsonl files in my directory.)

Is there any way to download the corresponding images?
Thanks.

**Comment by SeaOtocinclus** [comment]
Hello @taeyunwoo , you can look to our API in the https://github.com/facebookresearch/hot3d/blob/main/hot3d/HOT3D_Tutorial.ipynb Python notebook and see that you can use the hot3d_data_provider to retrieve `the device_data_provider` and retrieve frame from there
```
device_data_provider = hot3d_data_provider.device_data_provider
# Retrieve the image data for a given timestamp
image_data = device_data_provider.get_image(timestamp_ns, stream_id)
```

**Comment by taeyunwoo** [comment]
Sorry for bothering you.
I really appreciate your works!

Thank you for your reply.
I'll close this issue.

**Comment by SeaOtocinclus** [comment]
No worries at all, all questions are welcome ;-)
- We must surface this notebook better in the readme so our user can find it better.
